services:
  chroma-db:
    image: chromadb/chroma:latest
    container_name: vector-agent-chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma

  redis_memory:
    image: redis/redis-stack-server:latest
    container_name: agent-redis-memory
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  chroma_data:
  redis_data: