import os
import sys
from dotenv import load_dotenv
from langchain_community.document_loaders import PyMuPDFLoader, CSVLoader, TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Navigate 3 levels up to reach the root directory
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..'))
if ROOT_DIR not in sys.path:
    sys.path.append(ROOT_DIR)

from use_cases.vector_agent.src.vector_engine import VectorEngine

def process_file(file_path: str, collection_name: str, engine: VectorEngine):
    """Loads a file, splits it into chunks, and ingests it into ChromaDB."""
    print(f"\nProcessing file: {file_path}")
    
    # Choose the right loader based on file extension
    if file_path.endswith('.pdf'):
        loader = PyMuPDFLoader(file_path)
    elif file_path.endswith('.csv'):
        loader = CSVLoader(file_path, encoding='utf-8')
    elif file_path.endswith('.txt'):
        loader = TextLoader(file_path, encoding='utf-8')
    else:
        print(f"Unsupported file type: {file_path}")
        return

    # Load the raw document
    raw_documents = loader.load()
    print(f"-> Extracted {len(raw_documents)} raw pages/rows.")

    # Split the text into smaller, overlapping pieces
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,   # 1000 characters per chunk
        chunk_overlap=200, # 200 characters overlap with the previous chunk
        separators=["\n\n", "\n", ".", " "]
    )
    
    chunked_docs = text_splitter.split_documents(raw_documents)
    print(f"-> Split into {len(chunked_docs)} manageable chunks.")

    # Adapt to our VectorEngine format (texts and metadatas)
    texts = [doc.page_content for doc in chunked_docs]
    
    # We enrich the metadata generated by the loader (e.g., adding the source filename)
    metadatas = []
    for doc in chunked_docs:
        meta = doc.metadata
        meta["source_file"] = os.path.basename(file_path)
        metadatas.append(meta)
    
    batch_size = 50
    print(f"-> Sending to Azure and ChromaDB in batches of {batch_size}...")
    
    for i in range(0, len(texts), batch_size):
        batch_texts = texts[i:i + batch_size]
        batch_metadatas = metadatas[i:i + batch_size]
        
        print(f"Uploading batch {i//batch_size + 1} (Chunks {i} to {min(i + batch_size, len(texts))})...")
        try:
            engine.add_documents(texts=batch_texts, collection_name=collection_name, metadatas=batch_metadatas)
        except Exception as e:
            print(f"Error in batch {i//batch_size + 1}: {e}")

    print(f"Finished processing {file_path}\n")

def main():
    print("Starting  Data Ingestion...\n")
    load_dotenv()
    
    try:
        engine = VectorEngine()
    except Exception as e:
        print(f"Error initializing Vector Engine: {e}")
        return

    # Define the base data folder
    base_data_folder = os.path.join(os.path.dirname(__file__), '../data')
    
    if not os.path.exists(base_data_folder):
        print(f"Base data folder not found at: {base_data_folder}")
        return

    # Iterate dynamically over each subfolder inside 'data/'
    for folder_name in os.listdir(base_data_folder):
        folder_path = os.path.join(base_data_folder, folder_name)
        
        # Only process if it is actually a directory
        if os.path.isdir(folder_path):
            collection_name = folder_name
            print(f"Scanning directory: {folder_name}")
            
            # Iterate over all files inside this specific subfolder
            for file_name in os.listdir(folder_path):
                file_path = os.path.join(folder_path, file_name)
                
                # Only process files (ignore sub-directories or hidden system files)
                if os.path.isfile(file_path) and not file_name.startswith('.'):
                    process_file(file_path=file_path, collection_name=collection_name, engine=engine)

if __name__ == "__main__":
    main()